### ISSUE TITLE
More of a thank you than an issue

### ISSUE THREAD

**Issue by frankstallone** [joelparkerhenderson/brewfile#2]
I was looking for a starter `Brewfile` and forked this repo. Clearly you are a far superior developer than I am. I am shaving off items out of here like a wood chipper! Thank you though for putting all the time and energy into this! 

I do have a question though. There seems to be duplicates, I imagine you are aware? Docker is a good example. It's near the beginning and middle sections.

**Comment by joelparkerhenderson** [comment]
Thank you, you are so kind! 

Duplicates can be deleted, and also there's a bunch of TODO items. If you are interested in doing edits and sending a pull request, that's great and you'll show up on GitHub as a contributor to this repo. Or if you prefer to have me do the edits, that's good too.

**Comment by frankstallone** [comment]
Hey Joel! Thanks for the response. I am still figuring out how to use these bundles, like with `brew list` etc. correctly but wanted to start my own. I used yours as a springboard and shaved off a few thousand lines, so I don't think I am going to be very useful to you lol. How often do you run this?

**Comment by frankstallone** [comment]
Also, I was referring to duplicates outside of the dupes section. =)
